=== QIICR/dcmqi/doc/schemas/pm-schema.json
{
  "@context": "http://qiicr.org/dcmqi/contexts/dcmqi.jsonld",
  "id": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/pm-schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "required": [
    "AnatomicRegionSequence",
    "FrameLaterality",
    "QuantityValueCode",
    "MeasurementUnitsCode",
    "DerivationCode"
  ],
  "additionalProperties": false,
  "properties": {
    "@schema": {
      "type": "string"
    },
    "SeriesDescription": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "Parametric map"
    },
    "SeriesNumber": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS"
        }
      ],
      "default": "300"
    },
    "InstanceNumber": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS"
        }
      ],
      "default": "1"
    },
    "BodyPartExamined": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
        }
      ],
      "default": ""
    },
    "QuantityValueCode": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "MeasurementUnitsCode": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "MeasurementMethodCode": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "ModelFittingMethodCode": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "DerivationCode": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "DerivationDescription": {
      "type": "string",
      "default": ""
    },
    "SourceImageDiffusionBValues": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "RealWorldValueSlope": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/FD",
      "default": "1.0"
    },
    "AnatomicRegionSequence": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "FrameLaterality": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS",
      "default": "U"
    }
  }
}

=== QIICR/dcmqi/doc/examples/pm-example_no_modifier.json
{
  "SeriesDescription": "Parametric map",
  "SeriesNumber": "300",
  "InstanceNumber": "1",
  "BodyPartExamined": "Prostate",
  "AnatomicRegionSequence": {
    "CodeValue": "41216001",
    "CodingSchemeDesignator": "SCT",
    "CodeMeaning": "Prostate"
  },
  "QuantityValueCode": {
    "CodeValue": "126312",
    "CodingSchemeDesignator": "DCM",
    "CodeMeaning": "Ktrans"
  },
  "DerivationCode": {
    "CodeValue": "126312",
    "CodingSchemeDesignator": "DCM",
    "CodeMeaning": "Ktrans"
  },
  "MeasurementUnitsCode": {
    "CodeValue": "/min",
    "CodingSchemeDesignator": "UCUM",
    "CodeMeaning": "/min"
  },
  "DerivationDescription": "",
  "RealWorldValueSlope": "1",
  "FrameLaterality": "U"
}

=== QIICR/dcmqi/doc/examples/pm-example-float.json
{
  "@schema" : "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/pm-schema.json#",

  "SeriesDescription": "Apparent Diffusion Coefficient",
  "SeriesNumber": "701",
  "InstanceNumber": "1",
  "BodyPartExamined" : "PROSTATE",

  "QuantityValueCode": {
    "CodeValue": "113041",
    "CodingSchemeDesignator": "DCM",
    "CodeMeaning": "Apparent Diffusion Coefficient"
  },
  "DerivationCode": {
    "CodeValue": "113041",
    "CodingSchemeDesignator": "DCM",
    "CodeMeaning": "Apparent Diffusion Coefficient"
  },
  "MeasurementUnitsCode": {
    "CodeValue": "m2/s",
    "CodingSchemeDesignator": "UCUM",
    "CodeMeaning": "m2/s"
  },
  "MeasurementMethodCode": {
    "CodeValue": "113250",
    "CodingSchemeDesignator": "DCM",
    "CodeMeaning": "Mono-exponential diffusion model"
  },
  "SourceImageDiffusionBValues": ["0","1400"],
  "AnatomicRegionSequence": {
    "CodeValue": "41216001",
    "CodingSchemeDesignator": "SCT",
    "CodeMeaning": "Prostate"
  },
  "FrameLaterality" : "U",
  "RealWorldValueSlope" : "1"
}
