=== QIICR/dcmqi/doc/schemas/seg-schema.json
{
  "@context": "http://qiicr.org/dcmqi/contexts/dcmqi.jsonld",
  "id": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/seg-schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "@schema": {"type" : "string"},
    "ContentCreatorName": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/PN"
        }
      ],
      "default": "Reader1"
    },
    "ClinicalTrialSeriesID": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "Session1"
    },
    "ContentLabel": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
        }
      ],
      "default": "SEGMENTATION"
    },
    "ContentDescription": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "Image segmentation"
    },
    "ClinicalTrialCoordinatingCenterName": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "dcmqi"
    },
    "ClinicalTrialTimePointID": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "1"
    },
    "SeriesDescription": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
        }
      ],
      "default": "Segmentation"
    },
    "SeriesNumber": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS"
        }
      ],
      "default": "300"
    },
    "InstanceNumber": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS"
        }
      ],
      "default": "1"
    },
    "BodyPartExamined": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
        }
      ],
      "default": ""
    },
    "segmentAttributesFileMapping": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "segmentAttributes": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "labelID",
            "SegmentedPropertyCategoryCodeSequence",
            "SegmentedPropertyTypeCodeSequence",
            "SegmentAlgorithmType"
          ],
          "properties": {
            "labelID": {
              "type": "integer",
              "default": 1
            },
            "SegmentDescription": {
              "type": "string"
            },
            "SegmentedPropertyCategoryCodeSequence": {
              "allOf": [
                {
                  "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
                }
              ],
              "default": {
                "CodeValue": "T-D0050",
                "CodingSchemeDesignator": "SRT",
                "CodeMeaning": "Tissue"
              }
            },
            "SegmentedPropertyTypeCodeSequence": {
              "allOf": [
                {
                  "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
                }
              ],
              "default": {
                "CodeValue": "T-D0050",
                "CodingSchemeDesignator": "SRT",
                "CodeMeaning": "Tissue"
              }
            },
            "SegmentedPropertyTypeModifierCodeSequence": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
            },
            "AnatomicRegionSequence": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
            },
            "AnatomicRegionModifierSequence": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
            },
            "SegmentAlgorithmType": {
              "allOf": [
                {
                  "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
                },
                {
                  "enum": [
                    "AUTOMATIC",
                    "MANUAL",
                    "SEMIAUTOMATIC"
                  ]
                }
              ],
              "default": "SEMIAUTOMATIC"
            },
            "SegmentAlgorithmName": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO"
            },
            "recommendedDisplayRGBValue": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/RGB"
            },
            "RecommendedDisplayCIELabValue": {
              "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CIELab"
            }
          }
        }
      }
    }
  }
}

=== QIICR/dcmqi/doc/examples/seg-example_multiple_segments_single_input_file.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/seg-schema.json#",

  "ContentCreatorName": "Doe^John",
  "ClinicalTrialSeriesID": "Session1",
  "ClinicalTrialTimePointID": "1",
  "ClinicalTrialCoordinatingCenterName": "BWH",
  "SeriesDescription": "Segmentation",
  "SeriesNumber": "300",
  "InstanceNumber": "1",

  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentDescription": "Liver Segmentation",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "85756007",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Tissue"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "10200004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Liver"
        },
        "SegmentAlgorithmType": "SEMIAUTOMATIC",
        "SegmentAlgorithmName": "SlicerEditor",
        "recommendedDisplayRGBValue": [
          221,
          130,
          101
        ]
      },
      {
        "labelID": 2,
        "SegmentDescription": "Anatomical Structure",
        "SegmentedPropertyTypeCodeSequence": {
          "CodeMeaning": "Thoracic spine",
          "CodingSchemeDesignator": "SCT",
          "CodeValue": "122495006"
        },
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeMeaning": "Anatomical Structure",
          "CodingSchemeDesignator": "SCT",
          "CodeValue": "123037004"
        },
        "SegmentAlgorithmType": "MANUAL",
        "recommendedDisplayRGBValue": [
          226,
          202,
          134
        ]
      },
      {
        "labelID": 3,
        "SegmentDescription": "Anatomical Structure",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeMeaning": "Anatomical Structure",
          "CodingSchemeDesignator": "SCT",
          "CodeValue": "123037004"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeMeaning": "Heart",
          "CodingSchemeDesignator": "SCT",
          "CodeValue": "80891009"
        },
        "SegmentAlgorithmType": "MANUAL",
        "recommendedDisplayRGBValue": [
          206,
          110,
          84
        ]
      }
    ]
  ]
}

=== QIICR/dcmqi/doc/examples/bmmr-example.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/seg-schema.json#",

  "ContentCreatorName": "Reader1",
  "ClinicalTrialSeriesID": "Session1",
  "ClinicalTrialTimePointID": "1",
  "ClinicalTrialCoordinatingCenterName": "UCSF",
  "SeriesDescription": "Segmentation",
  "SeriesNumber": "300",
  "InstanceNumber": "1",

  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentAlgorithmType": "SEMIAUTOMATIC",
        "SegmentAlgorithmName": "Pre-contrast manual VOI",
        "SegmentDescription": "Breast segmentation",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "76752008",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Breast"
        },
        "SegmentedPropertyTypeModifierCodeSequence": {
          "CodeValue": "51440002",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Right and left"
        },
        "recommendedDisplayRGBValue": [
          252,
          226,
          234
        ]
      }
    ]
  ]
}

=== QIICR/dcmqi/doc/examples/seg-example_multiple_segments.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/seg-schema.json#",

  "ContentCreatorName": "Doe^John",
  "ClinicalTrialSeriesID": "Session1",
  "ClinicalTrialTimePointID": "1",
  "ClinicalTrialCoordinatingCenterName": "BWH",
  "SeriesDescription": "Segmentation",
  "SeriesNumber": "300",
  "InstanceNumber": "1",

  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentDescription": "Liver Segmentation",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "T-D0050",
          "CodingSchemeDesignator": "SRT",
          "CodeMeaning": "Tissue"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "T-62000",
          "CodingSchemeDesignator": "SRT",
          "CodeMeaning": "Liver"
        },
        "SegmentAlgorithmType": "SEMIAUTOMATIC",
        "SegmentAlgorithmName": "SlicerEditor",
        "recommendedDisplayRGBValue": [
          221,
          130,
          101
        ]
      }
    ],
    [
      {
        "labelID": 2,
        "SegmentDescription": "Anatomical Structure",
        "SegmentedPropertyTypeCodeSequence": {
          "CodeMeaning": "Thoracic spine",
          "CodingSchemeDesignator": "SRT",
          "CodeValue": "T-11502"
        },
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeMeaning": "Anatomical Structure",
          "CodingSchemeDesignator": "SRT",
          "CodeValue": "T-D000A"
        },
        "SegmentAlgorithmType": "MANUAL",
        "recommendedDisplayRGBValue": [
          226,
          202,
          134
        ]
      }
    ],
    [
      {
        "labelID": 3,
        "SegmentDescription": "Anatomical Structure",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeMeaning": "Anatomical Structure",
          "CodingSchemeDesignator": "SRT",
          "CodeValue": "T-D000A"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeMeaning": "Heart",
          "CodingSchemeDesignator": "SRT",
          "CodeValue": "T-32000"
        },
        "SegmentAlgorithmType": "MANUAL",
        "recommendedDisplayRGBValue": [
          206,
          110,
          84
        ]
      }
    ]
  ]
}
