=== QIICR/dcmqi/doc/schemas/sr-tid1500-schema.json
{
  "@context": "http://qiicr.org/dcmqi/contexts/dcmqi.jsonld",
  "id": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-tid1500-schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {

    "measurementModifier": {
      "type": "object",
      "properties": {
        "modifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "modifierValue": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        }
      }
    },

    "measurementNumProperty": {
      "type": "object",
      "properties": {
        "numProperty": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "numPropertyValue": {
          "type": "string"
        },
        "numPropertyUnits": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        }
      }
    },

    "measurementDerivationParameter": {
      "type": "object",
      "properties": {
        "derivationParameter": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "derivationParameterValue": {
          "type": "string"
        },
        "derivationParameterUnits": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        }
      }
    },

    "measurementItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/DS"
        },
        "quantity": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "units": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "derivationModifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },

        "measurementModifiers": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/measurementModifier"
          }
        },

        "measurementDerivationParameters": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/measurementDerivationParameter"
          }
        },

        "measurementNumProperties": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/measurementNumProperty"
          }
        },

        "measurementPopulationDescription": {
          "type": "string"
        },

        "measurementAlgorithmIdentification": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/measurementAlgorithmIdentification"
        }
      }
    },
    "qualitativeEvaluationItem":{
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "conceptCode": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "conceptValue": {
          "oneOf": [
            { "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence" },
            { "type": "string" }
          ]
        }
      }
    },

    "MeasurementGroup": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "TrackingIdentifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/TEXT"
        },
        "TrackingUniqueIdentifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/UIDREF"
        },
        "ReferencedSegment": {
          "type": "number"
        },
        "SourceSeriesForImageSegmentation": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/UIDREF"
        },
        "segmentationSOPInstanceUID": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/UIDREF"
        },
        "rwvmMapUsedForMeasurement": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/UIDREF"
        },
        "MeasurementMethod": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "Finding": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "FindingSite": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "Laterality": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
        },
        "measurementAlgorithmIdentification": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/measurementAlgorithmIdentification"
        },
        "measurementItems": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/measurementItem"
          }
        },
        "qualitativeEvaluations": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/qualitativeEvaluationItem"
          }
        }
      }
    },
    "referencedImageFileNames": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "properties": {
    "@schema": {"type" : "string"},
    "compositeContext": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/dicomInstancesFileNameList"
    },
    "imageLibrary": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/dicomInstancesFileNameList"
    },
    "observerContext": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-common-schema.json#/definitions/observerContext"
    },
    "activitySession": {
      "type": "string",
      "default": "1"
    },
    "timePoint": {
      "type": "string",
      "default": "1"
    },
    "measurementMethod": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "procedureReported": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/codeSequence"
    },
    "VerificationFlag": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
        },
        {
          "enum": [
            "VERIFIED",
            "UNVERIFIED"
          ]
        },
        {
          "default": "UNVERIFIED"
        }
      ]
    },
    "CompletionFlag": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/CS"
        },
        {
          "enum": [
            "PARTIAL",
            "COMPLETE"
          ]
        },
        {
          "default": "PARTIAL"
        }
      ]
    },
    "SeriesDescription": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/LO",
      "default": "Measurements"
    },
    "SeriesNumber": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS",
      "default": "400"
    },
    "InstanceNumber": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/common-schema.json#/definitions/IS",
      "default": "1"
    },
    "Measurements": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/MeasurementGroup"
      }
    }
  }
}

=== QIICR/dcmqi/doc/examples/sr-tid1500-example.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-tid1500-schema.json#",

  "SeriesDescription": "Measurements",
  "SeriesNumber": "1001",
  "InstanceNumber": "1",

  "compositeContext": [
    "rwvm.dcm",
    "seg.dcm"
  ],

  "imageLibrary": [
    "01.dcm",
    "02.dcm",
    "03.dcm"
  ],

  "observerContext": {
    "ObserverType": "PERSON",
    "PersonObserverName": "Reader1"
  },

  "VerificationFlag": "VERIFIED",
  "CompletionFlag": "COMPLETE",

  "activitySession": "1",
  "timePoint": "1",

  "Measurements": [
    {
      "TrackingIdentifier": "Measurements group 1",
      "ReferencedSegment": 1,
      "SourceSeriesForImageSegmentation": "1.3.6.1.4.1.14519.5.2.1.2744.7002.261560220703676715130542397405",
      "segmentationSOPInstanceUID": "1.2.276.0.7230010.3.1.4.8323329.18591.1440001312.777033",
      "rwvmMapUsedForMeasurement": "1.2.276.0.7230010.3.1.4.8323329.18215.1440001297.928457",
      "MeasurementMethod": {
        "CodeValue": "126401",
        "CodingSchemeDesignator": "DCM",
        "CodeMeaning": "SUV body weight calculation method"
      },
      "Finding": {
        "CodeValue": "86049000",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "Neoplasm, Primary"
      },
      "FindingSite": {
        "CodeValue": "55940004",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "pharyngeal tonsil (adenoid)"
      },
      "Laterality": {
        "CodeValue": "7771000",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "Left"
      },
      "measurementAlgorithmIdentification": {
        "AlgorithmName": "3D Slicer Editor effect (group level)",
        "AlgorithmVersion": "4.6 (group level)",
        "AlgorithmParameters": ["gamma: 2 (group level)"]
      },
      "measurementItems": [
        {
          "value": "1.96",
          "quantity": {
            "CodeValue": "126401",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "SUVbw"
          },
          "units": {
            "CodeValue": "{SUVbw}g/ml",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Standardized Uptake Value body weight"
          },
          "derivationModifier": {
            "CodeValue": "373098007",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Mean"
          },
          "measurementAlgorithmIdentification": {
            "AlgorithmName": "3D Slicer Editor effect",
            "AlgorithmVersion": "4.6",
            "AlgorithmParameters": ["gamma: 2"]
          }
        }
      ]
    }
  ]
}

=== QIICR/dcmqi/doc/examples/sr-tid1500-ct-liver-example.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-tid1500-schema.json#",

  "SeriesDescription": "Measurements",
  "SeriesNumber": "1001",
  "InstanceNumber": "1",

  "compositeContext": [
    "liver.dcm"
  ],

  "imageLibrary": [
    "01.dcm",
    "02.dcm",
    "03.dcm"
  ],

  "observerContext": {
    "ObserverType": "DEVICE",
    "DeviceObserverName": "SecretSauceGenerator",
    "DeviceObserverManufacturer": "The friends of friends",
    "DeviceObserverUID": "1.2.3.4"
  },

  "VerificationFlag": "UNVERIFIED",
  "CompletionFlag": "COMPLETE",

  "activitySession": "1",
  "timePoint": "1",

  "Measurements": [
    {
      "TrackingIdentifier": "Measurements group 1",
      "ReferencedSegment": 1,
      "SourceSeriesForImageSegmentation": "1.2.392.200103.20080913.113635.1.2009.6.22.21.43.10.23430.1",
      "segmentationSOPInstanceUID": "1.2.276.0.7230010.3.1.4.0.42154.1458337731.665796",
      "Finding": {
        "CodeValue": "113343008",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "Organ"
      },
      "FindingSite": {
        "CodeValue": "10200004",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "Liver"
      },
      "measurementAlgorithmIdentification": {
        "AlgorithmName": "3D Slicer Editor effect (group level)",
        "AlgorithmVersion": "4.6 (group level)",
        "AlgorithmParameters": ["gamma: 2 (group level)"]
      },
      "measurementItems": [
        {
          "value": "37.3289",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "measurementAlgorithmIdentification": {
            "AlgorithmName": "3D Slicer Editor effect (measurement level)",
            "AlgorithmVersion": "4.6 (measurement level)",
            "AlgorithmParameters": ["gamma: 2 (measurement level)"]
          },
          "derivationModifier": {
            "CodeValue": "373098007",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Mean"
          },
          "measurementModifiers": [
            {
              "modifier": {
                "CodeValue": "A.13",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Preprocessing operation"
              },
              "modifierValue": {
                "CodeValue": "A.14",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Top secret filter"
              }
            },
            {
              "modifier": {
                "CodeValue": "A.13b",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Preprocessing operation b"
              },
              "modifierValue": {
                "CodeValue": "A.14b",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Top secret filter b"
              }
            }

          ],

          "measurementDerivationParameters": [
            {
              "derivationParameter": {
                "CodeValue": "A.15",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Parameter A"
              },
              "derivationParameterValue": "9.91",
              "derivationParameterUnits": {
                "CodeValue": "A.16",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Cats"
              }
            },
            {
              "derivationParameter": {
                "CodeValue": "A.17",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Parameter B"
              },
              "derivationParameterValue": "2",
              "derivationParameterUnits": {
                "CodeValue": "A.18",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Elephants"
              }
             },
             {
              "derivationParameter": {
                "CodeValue": "A.19",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Parameter Z"
              },
              "derivationParameterValue": "1",
              "derivationParameterUnits": {
                "CodeValue": "A.20",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Apples"
              }
            }
          ],
          "measurementPopulationDescription": "Elves of the Black Forest",
          "measurementNumProperties": [
            {
              "numProperty": {
                "CodeValue": "1234",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Elf average weight"
              },
              "numPropertyValue": "10",
              "numPropertyUnits": {
                "CodeValue": "kg",
                "CodingSchemeDesignator": "UCUM",
                "CodeMeaning": "kilogram"
              }
            },
            {
              "numProperty": {
                "CodeValue": "1235",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Elf average height"
              },
              "numPropertyValue": "11",
              "numPropertyUnits": {
                "CodeValue": "cm",
                "CodingSchemeDesignator": "UCUM",
                "CodeMeaning": "centimeter"
              }
            }
          ]
        },
        {
          "value": "-778",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "255605001",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Minimum"
          },
          "measurementPopulationDescription": "Elves of the Black Forest 2",
          "measurementNumProperties": [
            {
              "numProperty": {
                "CodeValue": "1234",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Elf average weight"
              },
              "numPropertyValue": "20",
              "numPropertyUnits": {
                "CodeValue": "kg",
                "CodingSchemeDesignator": "UCUM",
                "CodeMeaning": "kilogram"
              }
            },
            {
              "numProperty": {
                "CodeValue": "1235",
                "CodingSchemeDesignator": "99TEST",
                "CodeMeaning": "Elf average height"
              },
              "numPropertyValue": "21",
              "numPropertyUnits": {
                "CodeValue": "cm",
                "CodingSchemeDesignator": "UCUM",
                "CodeMeaning": "centimeter"
              }
            }
          ]
        },
        {
          "value": "221",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "56851009",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Maximum"
          }
        },
        {
          "value": "59.1691",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "386136009",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Standard Deviation"
          }
        },
        {
          "value": "70361.9",
          "quantity": {
            "CodeValue": "118565006",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Volume"
          },
          "units": {
            "CodeValue": "mm3",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "cubic millimeter"
          }
        },
        {
          "value": "70.3619",
          "quantity": {
            "CodeValue": "118565006",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Volume"
          },
          "units": {
            "CodeValue": "cm3",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "cubic centimeter"
          }
        }
      ]
    }
  ]
}
