=== QIICR/dcmqi/doc/sr-tid1500-schema.json
{
  "@context": "http://qiicr.org/dcmqi/contexts/dcmqi.jsonld",
  "id": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-tid1500-schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "measurementItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/DS"
        },
        "quantity": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        },
        "units": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        },
        "derivationModifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        }
      }
    },
    "MeasurementGroup": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "TrackingIdentifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/TEXT"
        },
        "TrackingUniqueIdentifier": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/UIDREF"
        },
        "ReferencedSegment": {
          "type": "number"
        },
        "SourceSeriesForImageSegmentation": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/UIDREF"
        },
        "segmentationSOPInstanceUID": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/UIDREF"
        },
        "rwvmMapUsedForMeasurement": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/UIDREF"
        },
        "MeasurementMethod": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        },
        "Finding": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        },
        "FindingSite": {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codeSequence"
        },
        "measurementItems": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/measurementItem"
          }
        }
      }
    },
    "referencedImageFileNames": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "properties": {
    "@schema": {"type" : "string"},
    "compositeContext": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/dicomInstancesFileNameList"
    },
    "imageLibrary": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/dicomInstancesFileNameList"
    },
    "observerContext": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-common-schema.json#/definitions/observerContext"
    },
    "activitySession": {
      "type": "string",
      "default": "1"
    },
    "timePoint": {
      "type": "string",
      "default": "1"
    },
    "VerificationFlag": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/CS"
        },
        {
          "enum": [
            "VERIFIED",
            "UNVERIFIED"
          ]
        },
        {
          "default": "UNVERIFIED"
        }
      ]
    },
    "CompletionFlag": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/CS"
        },
        {
          "enum": [
            "PARTIAL",
            "COMPLETE"
          ]
        },
        {
          "default": "PARTIAL"
        }
      ]
    },
    "SeriesDescription": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/LO",
      "default": "Measurements"
    },
    "SeriesNumber": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/IS",
      "default": "400"
    },
    "InstanceNumber": {
      "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/IS",
      "default": "1"
    },
    "Measurements": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/MeasurementGroup"
      }
    },
    "CodingSchemeIdentificationSequence": {
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/codingSchemeIdentificationSequenceItem"
      }
    }
  }
}

=== QIICR/dcmqi/doc/sr-tid1500-ct-liver-example.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/sr-tid1500-schema.json#",

  "SeriesDescription": "Measurements",
  "SeriesNumber": "1001",
  "InstanceNumber": "1",

  "compositeContext": [
    "liver.dcm"
  ],

  "imageLibrary": [
    "01.dcm",
    "02.dcm",
    "03.dcm"
  ],

  "observerContext": {
    "ObserverType": "PERSON",
    "PersonObserverName": "Reader1"
  },

  "VerificationFlag": "VERIFIED",
  "CompletionFlag": "COMPLETE",

  "activitySession": "1",
  "timePoint": "1",

  "Measurements": [
    {
      "TrackingIdentifier": "Measurements group 1",
      "ReferencedSegment": 1,
      "SourceSeriesForImageSegmentation": "1.2.392.200103.20080913.113635.1.2009.6.22.21.43.10.23430.1",
      "segmentationSOPInstanceUID": "1.2.276.0.7230010.3.1.4.0.42154.1458337731.665796",
      "Finding": {
        "CodeValue": "T-D0060",
        "CodingSchemeDesignator": "SRT",
        "CodeMeaning": "Organ"
      },
      "FindingSite": {
        "CodeValue": "T-62000",
        "CodingSchemeDesignator": "SRT",
        "CodeMeaning": "Liver"
      },
      "measurementItems": [
        {
          "value": "37.3289",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "R-00317",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Mean"
          }
        },
        {
          "value": "-778",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "R-404FB",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Minimum"
          }
        },
        {
          "value": "221",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "G-A437",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Maximum"
          }
        },
        {
          "value": "59.1691",
          "quantity": {
            "CodeValue": "112031",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "Attenuation Coefficient"
          },
          "units": {
            "CodeValue": "[hnsf'U]",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Hounsfield unit"
          },
          "derivationModifier": {
            "CodeValue": "R-10047",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Standard Deviation"
          }
        },
        {
          "value": "70361.9",
          "quantity": {
            "CodeValue": "G-D705",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Volume"
          },
          "units": {
            "CodeValue": "mm3",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "cubic millimeter"
          }
        },
        {
          "value": "70.3619",
          "quantity": {
            "CodeValue": "G-D705",
            "CodingSchemeDesignator": "SRT",
            "CodeMeaning": "Volume"
          },
          "units": {
            "CodeValue": "cm3",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "cubic centimeter"
          }
        }
      ]
    }
  ]
}

=== QIICR/dcmqi/doc/examples/sr-tid1500-example-nan.json
{
  "@schema": "https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas/sr-tid1500-schema.json#",

  "SeriesDescription": "Measurements",
  "SeriesNumber": "1001",
  "InstanceNumber": "1",

  "compositeContext": [
    "rwvm.dcm",
    "seg.dcm"
  ],

  "imageLibrary": [
    "01.dcm",
    "02.dcm"
  ],

  "observerContext": {
    "ObserverType": "PERSON",
    "PersonObserverName": "Reader1"
  },

  "VerificationFlag": "VERIFIED",
  "CompletionFlag": "COMPLETE",

  "activitySession": "1",
  "timePoint": "1",

  "Measurements": [
    {
      "TrackingIdentifier": "Measurements group 1",
      "ReferencedSegment": 1,
      "SourceSeriesForImageSegmentation": "1.3.6.1.4.1.14519.5.2.1.2744.7002.261560220703676715130542397405",
      "segmentationSOPInstanceUID": "1.2.276.0.7230010.3.1.4.8323329.18591.1440001312.777033",
      "rwvmMapUsedForMeasurement": "1.2.276.0.7230010.3.1.4.8323329.18215.1440001297.928457",
      "MeasurementMethod": {
        "CodeValue": "126401",
        "CodingSchemeDesignator": "DCM",
        "CodeMeaning": "SUV body weight calculation method"
      },
      "Finding": {
        "CodeValue": "86049000",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "Neoplasm, Primary"
      },
      "FindingSite": {
        "CodeValue": "55940004",
        "CodingSchemeDesignator": "SCT",
        "CodeMeaning": "pharyngeal tonsil (adenoid)"
      },
      "measurementItems": [
        {
          "value": "nan",
          "quantity": {
            "CodeValue": "126401",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "SUVbw"
          },
          "units": {
            "CodeValue": "{SUVbw}g/ml",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Standardized Uptake Value body weight"
          },
          "derivationModifier": {
            "CodeValue": "373098007",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Mean"
          }
        },
        {
          "value": "1.23",
          "quantity": {
            "CodeValue": "126401",
            "CodingSchemeDesignator": "DCM",
            "CodeMeaning": "SUVbw"
          },
          "units": {
            "CodeValue": "{SUVbw}g/ml",
            "CodingSchemeDesignator": "UCUM",
            "CodeMeaning": "Standardized Uptake Value body weight"
          },
          "derivationModifier": {
            "CodeValue": "373098007",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Mean"
          }
        }
      ]
    }
  ]
}
